"""add contract fields

Revision ID: 1a81763741ff
Revises: fc1a653bf964
Create Date: 2024-11-29 13:25:37.547463

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1a81763741ff'
down_revision = 'fc1a653bf964'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.add_column(sa.Column('leave_reason', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('contract_number', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('contract_type', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('contract_duration', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('contract_start_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('contract_end_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('contract_sign_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('contract_status', sa.String(length=20), nullable=True))
        batch_op.alter_column('employee_no',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50),
               type_=sa.String(length=20),
               existing_nullable=False)
        batch_op.alter_column('gender',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=10),
               nullable=False)
        batch_op.alter_column('birth_date',
               existing_type=sa.DATE(),
               nullable=False)
        batch_op.alter_column('phone',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20),
               nullable=False)
        batch_op.alter_column('email',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=120),
               type_=sa.String(length=100),
               existing_nullable=True)
        batch_op.alter_column('id_card',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=18),
               nullable=False)
        batch_op.drop_index('user_id')
        batch_op.drop_constraint('employees_ibfk_1', type_='foreignkey')
        batch_op.drop_column('address')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('address', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=200), nullable=True))
        batch_op.create_foreign_key('employees_ibfk_1', 'users', ['user_id'], ['id'])
        batch_op.create_index('user_id', ['user_id'], unique=True)
        batch_op.alter_column('id_card',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=18),
               nullable=True)
        batch_op.alter_column('email',
               existing_type=sa.String(length=100),
               type_=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=120),
               existing_nullable=True)
        batch_op.alter_column('phone',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20),
               nullable=True)
        batch_op.alter_column('birth_date',
               existing_type=sa.DATE(),
               nullable=True)
        batch_op.alter_column('gender',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=10),
               nullable=True)
        batch_op.alter_column('employee_no',
               existing_type=sa.String(length=20),
               type_=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50),
               existing_nullable=False)
        batch_op.drop_column('contract_status')
        batch_op.drop_column('contract_sign_date')
        batch_op.drop_column('contract_end_date')
        batch_op.drop_column('contract_start_date')
        batch_op.drop_column('contract_duration')
        batch_op.drop_column('contract_type')
        batch_op.drop_column('contract_number')
        batch_op.drop_column('leave_reason')

    # ### end Alembic commands ###
